<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class DatabaseBackup extends Command
{
    protected $signature = 'db:backup {--filename=backup.sql}';
    protected $description = 'Create a MySQL dump of the database';

    public function handle()
    {
        $filename = $this->option('filename');
        $ds = DIRECTORY_SEPARATOR;
        
        $host = config('database.connections.mysql.host');
        $database = config('database.connections.mysql.database');
        $username = config('database.connections.mysql.username');
        $password = config('database.connections.mysql.password');
        
        $backupPath = database_path('backups');
        
        if (!is_dir($backupPath)) {
            mkdir($backupPath, 0755, true);
        }
        
        $fullPath = $backupPath . $ds . $filename;
        
        $this->info('Creating database backup using PHP...');
        
        try {
            $pdo = new \PDO(
                "mysql:host={$host};dbname={$database}",
                $username,
                $password,
                [\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION]
            );
            
            $dump = "-- MySQL dump generated by Laravel\n";
            $dump .= "-- Date: " . date('Y-m-d H:i:s') . "\n\n";
            $dump .= "SET FOREIGN_KEY_CHECKS=0;\n\n";
            
            // Get all tables
            $tables = $pdo->query("SHOW TABLES")->fetchAll(\PDO::FETCH_COLUMN);
            
            foreach ($tables as $table) {
                $this->line("Backing up table: {$table}");
                
                // Drop table statement
                $dump .= "DROP TABLE IF EXISTS `{$table}`;\n";
                
                // Create table statement
                $createTable = $pdo->query("SHOW CREATE TABLE `{$table}`")->fetch(\PDO::FETCH_ASSOC);
                $dump .= $createTable['Create Table'] . ";\n\n";
                
                // Get table data
                $rows = $pdo->query("SELECT * FROM `{$table}`")->fetchAll(\PDO::FETCH_ASSOC);
                
                if (!empty($rows)) {
                    foreach ($rows as $row) {
                        $values = array_map(function($value) use ($pdo) {
                            return $value === null ? 'NULL' : $pdo->quote($value);
                        }, array_values($row));
                        
                        $dump .= "INSERT INTO `{$table}` VALUES (" . implode(',', $values) . ");\n";
                    }
                    $dump .= "\n";
                }
            }
            
            $dump .= "SET FOREIGN_KEY_CHECKS=1;\n";
            
            file_put_contents($fullPath, $dump);
            
            $this->info("Database backup created successfully: {$fullPath}");
            $this->info("File size: " . number_format(filesize($fullPath) / 1024 / 1024, 2) . " MB");
            
            return 0;
            
        } catch (\Exception $e) {
            $this->error('Database backup failed: ' . $e->getMessage());
            return 1;
        }
    }
}
