services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - BETTERSTACK_SOURCE_TOKEN=${BETTERSTACK_SOURCE_TOKEN}
    networks:
      - laravel

networks:
  laravel:
    driver: bridge